apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: flightctl-alertmanager
  name: flightctl-alertmanager
  namespace: '{{ default "{{ .Values.global.namespace }}" .Values.global.namespace }}'
spec:
  ports:
  - name: '9093'
    port: 9093
    targetPort: 9093
  selector:
    flightctl.service: flightctl-alertmanager
