apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flightctl
    app.kubernetes.io/version: latest
    flightctl.service: flightctl-api
    helm.sh/chart: flightctl-0.1.0
  name: flightctl-api-agent
  namespace: '{{ .Values.global.namespace }}'
spec:
  ports:
  - name: agent-api
    port: 7443
    targetPort: 7443
  selector:
    flightctl.service: flightctl-api
