apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flightctl-alertmanager-proxy-route
  namespace: '{{ default "{{ .Values.global.namespace }}" .Values.global.namespace }}'
spec:
  host: alertmanager-proxy.{{ .Values.global.baseDomain }}
  port:
    targetPort: 8443
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: flightctl-alertmanager-proxy
    weight: 100
  wildcardPolicy: None
