apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: flightctl-db-migration
    security.level: schema-privilege
  name: flightctl-db-migration-schema-access
  namespace: '{{ default "{{ .Values.global.namespace }}" .Values.global.namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flightctl-db-migration-access
subjects:
- kind: ServiceAccount
  name: flightctl-db-migration
  namespace: '{{ default "{{ .Values.global.namespace }}" .Values.global.namespace }}'
