apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flightctl-api-route
  namespace: '{{ default "default" .Values.global.namespace }}'
spec:
  host: api.test
  port:
    targetPort: 3443
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: flightctl-api
    weight: 100
  wildcardPolicy: None
