
# Source: flightctl/charts/ui/templates/flightctl-ui-certs-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui-certs
  namespace: open-cluster-management
type: Opaque
stringData:
  ca.crt: ""
