apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: flightctl-api
  name: flightctl-api-agent
  namespace: '{{ default "default" .Values.global.namespace }}'
spec:
  ports:
  - name: agent-api
    port: 7443
    targetPort: 7443
  selector:
    flightctl.service: flightctl-api
