apiVersion: v1
data:
  config.yaml: "database:\n  hostname: flightctl-db.{{ .Values.global.namespace }}.svc.cluster.local\n  name: flightctl\n  port: 5432\n  type: pgsql\nkv:\n  hostname: flightctl-kv.{{ .Values.global.namespace }}.svc.cluster.local\n  port: 6379\nperiodic:\n  consumers: 5\nservice: {}\n"
kind: ConfigMap
metadata:
  name: flightctl-periodic-config
  namespace: '{{ .Values.global.namespace  }}'
