apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: flightctl-db-app
    security.level: application
  name: flightctl-db-app-access
  namespace: '{{ default "''{{ .Values.global.namespace }}''" .Values.global.namespace }}'
rules:
- apiGroups:
  - ''
  resourceNames:
  - flightctl-db-app-secret
  resources:
  - secrets
  verbs:
  - get
