apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: flightctl-job-status
  name: flightctl-job-status-reader
  namespace: '{{ .Values.global.namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flightctl-job-status-reader
subjects:
- kind: ServiceAccount
  name: flightctl-worker
  namespace: '{{ .Values.global.namespace }}'
- kind: ServiceAccount
  name: flightctl-periodic
  namespace: '{{ .Values.global.namespace }}'
- kind: ServiceAccount
  name: flightctl-alert-exporter
  namespace: '{{ .Values.global.namespace }}'
- kind: ServiceAccount
  name: flightctl-api
  namespace: '{{ .Values.global.namespace }}'
- kind: ServiceAccount
  name: flightctl-alertmanager-proxy
  namespace: '{{ .Values.global.namespace }}'
