apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: backup-restore-oadp
  namespace: open-cluster-management-backup
  labels:
    app: cluster-backup-chart
    chart: cluster-backup-chart
    release: cluster-backup-chart
    heritage: Helm
    app.kubernetes.io/instance: cluster-backup-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster-backup-chart
    helm.sh/chart: cluster-backup-chart
    velero.io/exclude-from-backup: "true"
    component: policy
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-4 Backups of information are conducted maintained and tested
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/source: system
spec:
  disabled: true
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-oadp
        spec:
          object-templates-raw: |
            {{` {{- /* Check cluster platform  */ -}}` }}
            {{` {{- $platformType := ""}}` }}
            {{` {{- range $infra := (lookup "config.openshift.io/v1" "Infrastructure" "" "" "").items }}` }}
              {{` {{ if eq $infra.metadata.name "cluster" }}` }}
                {{` {{- $platformType = $infra.status.platform }}` }}
              {{` {{- end }}` }}
            {{` {{- end }}` }}

            {{` {{- /* Get credentials mode value  */ -}}` }}
            {{` {{- $credentialsMode := ""}}` }}
            {{` {{- range $cloud_cred := (lookup "operator.openshift.io/v1" "CloudCredential" "" "" "").items }}` }}
              {{` {{ if eq $cloud_cred.metadata.name "cluster" }}` }}
                {{` {{- $credentialsMode = $cloud_cred.spec.credentialsMode }}` }}
              {{` {{- end }}` }}
            {{` {{- end }}` }}
            
            {{` {{- /* Check cluster serviceAccountIssuer value  */ -}}` }}
            {{` {{- $serviceAccountIssuer := ""}}` }}
            {{` {{- range $auth := (lookup "config.openshift.io/v1" "Authentication" "" "" "").items }}` }}
              {{` {{ if eq $auth.metadata.name "cluster" }}` }}
                {{` {{- $serviceAccountIssuer = $auth.spec.serviceAccountIssuer }}` }}
              {{` {{- end }}` }}
            {{` {{- end }}` }}

            {{` {{- /* Check oadp-manual option set on on cluster  */ -}}` }}
            {{` {{- $manualInstall := ""}}` }}
            {{` {{- range $cclaim := (lookup "cluster.open-cluster-management.io/v1alpha1" "ClusterClaim" "" "" "").items }}` }}
              {{` {{ if eq $cclaim.metadata.name "oadp-manual" }}` }}
                {{` {{- $manualInstall = $cclaim.spec.value }}` }}
              {{` {{- end }}` }}
            {{` {{- end }}` }}           

            {{` {{- $isSTSEnabledCluster := and (eq $credentialsMode "Manual")  (not (eq $serviceAccountIssuer "")) (eq (lower $platformType) "aws")}}` }}
            {{` {{- $isManualInstall :=  eq (lower $manualInstall) "true" }}` }}

            {{` {{ if not (or $isManualInstall  $isSTSEnabledCluster) }}` }}
              {{` {{- /* This is not an STS enabled cluster and the user did not set the manual install label - can install OADP  */ -}}` }}
              {{` {{- /* Creates the OADP Operator namespace group  */ -}}` }}
              {{` {{- /* All operator resources will be installed under the open-cluster-management-backup namespace  */ -}}` }}

            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  namespace: open-cluster-management-backup
                  name: redhat-oadp-operator-group
                spec:
                  targetNamespaces:
                  - open-cluster-management-backup
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  namespace: open-cluster-management-backup
                  name: redhat-oadp-operator-subscription
                spec:
                  channel: {{ .Values.global.channel }}
                  config:
                    resources: {}
                {{- with .Values.hubconfig.nodeSelector }}
                    nodeSelector:
                {{ toYaml . | indent 22 }}
                {{- end }}
                {{- with .Values.hubconfig.tolerations }}
                    tolerations:
                    {{- range . }}
                    - {{ if .Key }} key: {{ .Key }} {{- end }}
                      {{ if .Operator }} operator: {{ .Operator }} {{- end }}
                      {{ if .Value }} value: {{ .Value }} {{- end }}
                      {{ if .Effect }} effect: {{ .Effect }} {{- end }}
                      {{ if .TolerationSeconds }} tolerationSeconds: {{ .TolerationSeconds }} {{- end }}
                      {{- end }}
                {{- end }}
                    {{- if .Values.hubconfig.proxyConfigs }}
                    env:
                    - name: HTTP_PROXY
                      value: {{ .Values.hubconfig.proxyConfigs.HTTP_PROXY }}
                    - name: HTTPS_PROXY
                      value: {{ .Values.hubconfig.proxyConfigs.HTTPS_PROXY }}
                    - name: NO_PROXY
                      value: {{ .Values.hubconfig.proxyConfigs.NO_PROXY }}
                    {{- end }}
                  installPlanApproval: {{ .Values.global.installPlanApproval}}
                  name: {{ .Values.global.name }}
                  source: {{ .Values.global.source }}
                  sourceNamespace: {{ .Values.global.sourceNamespace }} 
            {{` {{- end }}` }}             
          remediationAction: enforce
          severity: high
