# Copyright Contributors to the Open Cluster Management project
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-backup-chart-webhook-service
  namespace: open-cluster-management-backup
  labels:
    app: cluster-backup-chart
    chart: cluster-backup-chart
    component: "clusterbackup"
    release: cluster-backup-chart
  annotations:
    # OpenShift Service CA will automatically generate TLS certs for this service
    service.beta.openshift.io/serving-cert-secret-name: cluster-backup-webhook-cert
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: cluster-backup-chart
    component: "clusterbackup"

