apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  labels:
    app: cluster-backup-chart
    chart: cluster-backup-chart
    release: cluster-backup-chart
    heritage: Helm
    app.kubernetes.io/instance: cluster-backup-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster-backup-chart
    helm.sh/chart: cluster-backup-chart
    velero.io/exclude-from-backup: "true"
    component: policy
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-4 Backups of information are conducted maintained and tested
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/source: system
  name: backup-restore-enabled
  namespace: open-cluster-management-backup
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    app: cluster-backup-chart
                  namespace: open-cluster-management-backup
                status:
                  phase: Running
          remediationAction: inform
          severity: high
          customMessage:
            noncompliant: |-
              The cluster-backup-chart-clusterbackup pod is either not running in the open-cluster-management-backup namespace or there is an error. 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oadp-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  annotations:
                    repository: https://github.com/openshift/oadp-operator
                  namespace: open-cluster-management-backup
                status:
                  phase: Running
          customMessage:
            noncompliant: |-
              The openshift-adp-controller-manager pod is either not running in the open-cluster-management-backup namespace or there is an error. 
              If the openshift-adp-controller-manager pod is not running in the open-cluster-management-backup namespace, check the 
              multiclusterhub-operator pod for errors related to the OADP operator installation.
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: velero-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    app.kubernetes.io/name: velero
                  namespace: open-cluster-management-backup
                status:
                  phase: Running
          customMessage:
            noncompliant: |-
              The velero pod is either not running in the open-cluster-management-backup namespace or there is an error. 
              Velero is installed by the oadp.openshift.io.DataProtectionApplication resource, so if the pod is not running,
              verify that you have a valid oadp.openshift.io.DataProtectionApplication resource in the open-cluster-management-backup namespace.
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: data-protection-application-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: oadp.openshift.io/v1alpha1
                kind: DataProtectionApplication
                metadata:
                  namespace: open-cluster-management-backup
          customMessage:
            compliant: "The oadp.openshift.io.DataProtectionApplication resource exists in the open-cluster-management-backup namespace."
            noncompliant: |-
              The oadp.openshift.io.DataProtectionApplication resource does not exist in the open-cluster-management-backup namespace. 
              You must create this resource to connect to the backup storage location.
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: backup-storage-location-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: BackupStorageLocation
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: Available
          customMessage:
            compliant: "The velero.io.BackupStorageLocation resource exists in the open-cluster-management-backup namespace and the phase is Available."
            noncompliant: |-
              The velero.io.BackupStorageLocation resource with a phase Available does not exist in the open-cluster-management-backup namespace. 
              This resource is created by the oadp.openshift.io.DataProtectionApplication resource, so verify that you have 
              a DataProtectionApplication resource in the open-cluster-management-backup namespace that has valid content.
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: backup-schedule-cron-enabled
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  labels:
                    velero.io/schedule-name: acm-validation-policy-schedule
                  namespace: open-cluster-management-backup
          customMessage:
            compliant: "Template is compliant, a BackupSchedule is active and generating hub backups at the specified storage location."
            noncompliant: |-
              Template is not compliant, there is no backup schedule actively running and generating hub backups at the specified storage location.
              Verify that you have a hub, connected to the specified storage location, with a BackupSchedule resource active and generating hub backup.
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-managed-clusters-schedule-backups-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: open-cluster-management-backup
                  labels:
                    velero.io/schedule-name: acm-managed-clusters-schedule
                status:
                  phase: Completed
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-resources-schedule-backups-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: open-cluster-management-backup
                  labels:
                    velero.io/schedule-name: acm-resources-schedule
                status:
                  phase: Completed
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-in-progress-report
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: InProgress 
          customMessage:
            compliant: |- 
              Template is compliant, no Backup with an InProgress status found.  This template is useful to identify backups unable to complete.                                                        
          remediationAction: inform
          severity: medium
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-clusters-collision-report
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: BackupCollision
          customMessage:
            compliant: "The BackupSchedule resource with a BackupCollision status does not exist."
          remediationAction: inform
          severity: high   
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-phase-validation
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: FailedValidation 
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: Failed 
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: ""
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Restore
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: ""
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Restore
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: Error
          customMessage:
            compliant: |-
              The BackupSchedule resource with a status of Failed, FailedValidation or empty value does not exist.
              The cluster.open-cluster-management.io.Restore resource with a status of Error or empty value also does not exist.                                                   
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oadp-operator-exists
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  namespace: open-cluster-management-backup
                spec:
                  name: redhat-oadp-operator
          customMessage:
            noncompliant: |-
              The redhat-oadp-operator subscription does not exist in the open-cluster-management-backup namespace.
              If this hub cluster does not have the AWS Security Token Service (STS) option enabled,
              OADP is installed by the MultiClusterHub resource when the cluster-backup option is set to true.
              Check the multiclusterhub-operator pod for errors related to the OADP operator installation. 
              For hub clusters where the STS option is enabled, you must manually install the OADP operator.
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oadp-channel-validation
        spec:
          remediationAction: inform
          severity: high
          object-templates-raw: |
            {{ printf `{{- $ch := "%s" }}` .Values.global.minOADPChannel }}
            {{ `{{- range $ss := (lookup "operators.coreos.com/v1alpha1" "Subscription" "open-cluster-management-backup" "").items }}` }}
              {{ `{{- if and (eq $ss.spec.name "redhat-oadp-operator") (lt $ss.spec.channel $ch) }}` }}
              - complianceType: musthave
                objectDefinition:
                  kind: Subscription
                  apiVersion: operators.coreos.com/v1alpha1
                  metadata:
                    name: {{ `{{ $ss.metadata.name }}` }}
                    namespace: {{ `{{ $ss.metadata.namespace }}` }}
                  spec:
                    channel: {{ `{{ $ch }}` }}
              {{ `{{- end }}` }}
            {{ `{{- end }}` }}
          customMessage:
            compliant: |- 
              The redhat-oadp-operator subscription installation does not exist in the open-cluster-management-backup namespace, 
              or the installed version matches or exceeds the version set by the backup and restore operator Helm chart.
            noncompliant: 
              The version of the redhat-oadp-operator operator installed in the open-cluster-management-backup namespace 
              is lower than the version set by the backup and restore operator Helm chart.
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: custom-oadp-channel-validation
        spec:
          remediationAction: inform
          severity: high
          object-templates-raw: |
            {{ `{{- $ch := "" }}` }}
            {{ `{{- range $ss := (lookup "operators.coreos.com/v1alpha1" "Subscription" "open-cluster-management-backup" "").items }}` }}
              {{ `{{- if (eq $ss.spec.name "redhat-oadp-operator") }}` }}
                {{ `{{ $ch = $ss.spec.channel }}` }}
                {{ `{{- break }}` }}
              {{ `{{- end }}` }}
            {{ `{{- end }}` }}
            {{ `{{- if $ch }}` }}
              {{ `{{- range $cs := (lookup "operators.coreos.com/v1alpha1" "Subscription" "" "").items }}` }}
                {{ `{{- if and (eq $cs.spec.name "redhat-oadp-operator") (ne $cs.spec.channel $ch) }}` }}
                - complianceType: musthave
                  objectDefinition:
                    kind: Subscription
                    apiVersion: operators.coreos.com/v1alpha1
                    metadata:
                      name: {{ `{{ $cs.metadata.name }}` }}
                      namespace: {{ `{{ $cs.metadata.namespace }}` }}
                    spec:
                      channel: {{ `{{ $ch }}` }}
                {{ `{{- end }}` }}
              {{ `{{- end }}` }}
            {{ `{{- end }}` }}
          customMessage:
            compliant: |- 
              There is no redhat-oadp-operator subscription installed in a namespace other than the open-cluster-management-backup namespace,
              or a redhat-oadp-operator subscription is installed and matches the version of the redhat-oadp-operator subscription installed within the open-cluster-management-backup namespace.
            noncompliant: |-
              There is a version of redhat-oadp-operator subscription installed in a namespace other than the open-cluster-management-backup namespace
              and this version doesn't match the version set by the backup and restore operator Helm chart.
              Alternatively, the version doesn't match the version of the redhat-oadp-operator subscription that is installed within the open-cluster-management-backup namespace.
  remediationAction: inform