apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: acm-hub-backup
  namespace: open-cluster-management-backup
spec:
  description: ACM Hub backup and restore. Includes policies to run Hub PVC backup and restore using VolSync with the restic mover feature, leveraging CSI volume snapshot.
  policies:
    - backup-restore-enabled
    - backup-restore-auto-import
    - backup-pvc-config
    - backup-pvc-source
    - backup-pvc-destination
