apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  annotations:
    addon.open-cluster-management.io/lifecycle: gitops-addon
  name: gitops-addon
spec:
  addOnMeta:
    description: gitops-addon
    displayName: gitops-addon
  supportedConfigs:
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
  - defaultConfig:
      name: gitops-addon
    group: addon.open-cluster-management.io
    resource: addontemplates
