# Copyright Contributors to the Open Cluster Management project

apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: acm
spec:
  displayName: Red Hat Advanced Cluster Management
  backend:
    service:
      basePath: /plugin/
      name: console-chart-console-v2
      namespace: {{ .Values.global.namespace }}
      port: 3000
    type: Service
  i18n:
    loadType: Preload
  proxy:
    - alias: console
      authorization: UserToken
      endpoint:
        service:
          name: console-chart-console-v2
          namespace: {{ .Values.global.namespace }}
          port: 3000
        type: Service
