# Copyright Contributors to the Open Cluster Management project

---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: release-2.6
    apps.open-cluster-management.io/git-path: clusterImageSets/fast
  labels:
    app: hive-clusterimagesets
    subscription-pause: {{ .Values.clusterImageSets.subscriptionPause | quote }}
  name: hive-clusterimagesets-subscription-fast-0
spec:
  channel: {{ .Values.global.namespace }}/acm-hive-openshift-releases-chn-0
  placement:
    local: true
