
# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

org: open-cluster-management

global:
  pullSecret: null
  imageOverrides:
    imageOverride: ""
  namespace: default
    
hubconfig:
  nodeSelector: null
  replicaCount: 1
  proxyConfigs: {}
  tolerations: []
