global:
  hubSize: Small
  imageOverrides:
    flightctl_api: ''
    flightctl_ocp_ui: ''
    flightctl_periodic: ''
    flightctl_worker: ''
    postgresql_12_c8s: ''
  namespace: default
  pullSecret: null
  templateOverrides: {}
hubconfig:
  clusterSTSEnabled: false
  nodeSelector: null
  ocpVersion: 4.12.0
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
