global:
  apiUrl: ''
  baseDomain: ''
  hubSize: Small
  imageOverrides:
    alertmanager: ''
    flightctl_alert_exporter: ''
    flightctl_alertmanager_proxy: ''
    flightctl_api: ''
    flightctl_cli_artifacts: ''
    flightctl_ocp_ui: ''
    flightctl_periodic: ''
    flightctl_worker: ''
    origin_cli: ''
    postgresql_16: ''
    redis_7_c9s: ''
  namespace: default
  pullSecret: null
  templateOverrides: {}
hubconfig:
  clusterSTSEnabled: false
  nodeSelector: null
  ocpVersion: 4.12.0
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
