# Copyright (c) 2022 Red Hat, Inc.

apiVersion: v1
name: volsync-addon-controller
description: Helm chart for the Volsync Addon Controller
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - acm
  - volsync
  - backup
  - csi
  - data
  - disaster recovery
  - replication
  - storage
