apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  annotations:
    addon.open-cluster-management.io/lifecycle: addon-manager
  labels:
    velero.io/exclude-from-backup: 'true'
  name: acm-roles
spec:
  addOnMeta:
    description: ACM Roles
    displayName: ACM Roles
  installStrategy:
    placements:
    - name: global
      namespace: open-cluster-management-global-set
    type: Placements
  supportedConfigs:
  - defaultConfig:
      name: acm-roles
    group: addon.open-cluster-management.io
    resource: addontemplates
