apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-roles-placement
  namespace: open-cluster-management-global-set
  labels:
    velero.io/exclude-from-backup: 'true'
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector: {}
