apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: multiclusterhub-operator
    app.kubernetes.io/name: multicluster-role-assignment
    velero.io/exclude-from-backup: 'true'
  name: multicluster-role-assignment-controller
