apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: multiclusterhub-operator
    app.kubernetes.io/name: multicluster-role-assignment
    velero.io/exclude-from-backup: 'true'
  name: '{{ .Values.org }}:{{ .Chart.Name }}:fine-grained-rbac'
  namespace: '{{ default "default" .Values.global.namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ .Values.org }}:{{ .Chart.Name }}:fine-grained-rbac'
subjects:
- kind: ServiceAccount
  name: multicluster-role-assignment-controller
  namespace: '{{ default "default" .Values.global.namespace }}'
