apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    open-cluster-management.io/policy-cnv: virt-rbac
  name: placement-policy-virt-rbac
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: environment
          operator: In
          values:
          - virtualization
  tolerations:
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
