apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: cnv-config
  namespace: '{{ .Values.global.namespace }}'
spec:
  agentInstallNamespace: openshift-cnv
  customizedVariables:
  - name: LIVE_NETWORK_KEY
  - name: LIVE_NETWORK_VALUE
