apiVersion: addon.open-cluster-management.io/v1beta1
kind: ClusterManagementAddOn
metadata:
  annotations:
    addon.open-cluster-management.io/lifecycle: addon-manager
  name: kubevirt-hyperconverged
spec:
  addOnMeta:
    description: Kubevirt Hyperconverged
    displayName: Kubevirt Hyperconverged
  defaultConfigs:
  - group: addon.open-cluster-management.io
    name: kubevirt-hyperconverged
    resource: addontemplates
  installStrategy:
    placements:
    - name: openshift-cnv
      namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
    type: Placements
