apiVersion: addon.open-cluster-management.io/v1beta1
kind: ClusterManagementAddOn
metadata:
  annotations:
    addon.open-cluster-management.io/lifecycle: addon-manager
  name: mtv-operator
spec:
  addOnMeta:
    description: MTV Operator
    displayName: MTV Operator
  defaultConfigs:
  - group: addon.open-cluster-management.io
    name: mtv-operator
    resource: addontemplates
  installStrategy:
    placements:
    - name: openshift-mtv
      namespace: '{{ default "open-cluster-management" .Values.global.namespace }}'
    type: Placements
