kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcm-apiserver
  labels:
    app: mcm-apiserver
spec:
  selector:
    matchLabels:
      app: mcm-apiserver
  template:
    metadata:
      labels:
        app: mcm-apiserver
    spec:
      serviceAccountName: hub-sa
      replicas: 1
      volumes: []
      containers:
      - name: mcm-apiserver
        image: multicloud-manager:0.0.1
        volumeMounts: []
        env: []
        args:
          - "/mcm-apiserver"
          - "--mongo-database=mcm"
          - "--enable-admission-plugins=HCMUserIdentity,KlusterletCA,NamespaceLifecycle"
          - "--secure-port=6443"
          - "--tls-cert-file=/var/run/apiserver/tls.crt"
          - "--tls-private-key-file=/var/run/apiserver/tls.key"
          - "--klusterlet-cafile=/var/run/klusterlet/ca.crt"
          - "--klusterlet-certfile=/var/run/klusterlet/tls.crt"
          - "--klusterlet-keyfile=/var/run/klusterlet/tls.key"
          - "--http2-max-streams-per-connection=1000"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "2048Mi"
