apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-operators-cluster-controller
  namespace: multicloud-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicloud-operators-cluster-controller
  template:
    metadata:
      labels:
        name: multicloud-operators-cluster-controller
    spec:
      serviceAccountName: multicloud-operators-cluster-controller
      containers:
        - name: multicloud-operators-cluster-controller
          image: multicloud-operators-cluster-controller:latest
          command:
          - multicloud-operators-cluster-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicloud-operators-cluster-controller"
