namespace: open-cluster-management
images: # updates operator.yaml with the dev image
- name: multiclusterhub-operator
  newName: quay.io/rhibmcollab/multiclusterhub-operator
  newTag: 2.2.9
resources:
- role.yaml
- role_binding.yaml
- service_account.yaml
- operator.yaml
