apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: multiclusterhub-operator
rules:
- apiGroups:
  - ""
  - "admissionregistration.k8s.io"
  - "apiextensions.k8s.io"
  - "apiregistration.k8s.io"
  - "apps"
  - "apps.open-cluster-management.io"
  - "authorization.k8s.io"
  - "hive.openshift.io"
  - "mcm.ibm.com"
  - "proxy.open-cluster-management.io"
  - "rbac.authorization.k8s.io"
  - "security.openshift.io"
  resources:
  - apiservices
  - channels
  - clusterjoinrequests
  - clusterrolebindings
  - clusterstatuses/log
  - configmaps
  - customresourcedefinitions
  - deployments
  - hiveconfigs
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - namespaces
  - pods
  - replicasets
  - rolebindings
  - secrets
  - serviceaccounts
  - services
  - subjectaccessreviews
  - subscriptions
  - helmreleases
  verbs:
  - get

- apiGroups:
  - ""
  - "admissionregistration.k8s.io"
  - "apiextensions.k8s.io"
  - "apiregistration.k8s.io"
  - "apps"
  - "apps.open-cluster-management.io"
  - "authorization.k8s.io"
  - "hive.openshift.io"
  - "monitoring.coreos.com"
  - "rbac.authorization.k8s.io"
  - "mcm.ibm.com"
  - "security.openshift.io"
  resources:
  - apiservices
  - channels
  - clusterjoinrequests
  - clusterrolebindings
  - clusterroles
  - configmaps
  - customresourcedefinitions
  - deployments
  - hiveconfigs
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  - namespaces
  - rolebindings
  - secrets
  - serviceaccounts
  - services
  - servicemonitors
  - subjectaccessreviews
  - subscriptions
  - validatingwebhookconfigurations
  verbs:
  - create
  - update

- apiGroups:
  - ""
  - "apps"
  - "apps.open-cluster-management.io"
  - "admissionregistration.k8s.io"
  - "apiregistration.k8s.io"
  - "authorization.k8s.io"
  - "config.openshift.io"
  - "mcm.ibm.com"
  - "operator.open-cluster-management.io"
  - "rbac.authorization.k8s.io"
  resources:
  - apiservices
  - clusterjoinrequests
  - configmaps
  - deployments
  - helmreleases
  - ingresses
  - multiclusterhubs
  - namespaces
  - rolebindings
  - servicemonitors
  - secrets
  - services
  - subjectaccessreviews
  - subscriptions
  - validatingwebhookconfigurations
  verbs:
  - list

- apiGroups:
  - ""
  - "admissionregistration.k8s.io"
  - "apiregistration.k8s.io"
  - "apps"
  - "authorization.k8s.io"
  - "config.openshift.io"
  - "mcm.ibm.com"
  - "operator.open-cluster-management.io"
  - "rbac.authorization.k8s.io"
  - "storage.k8s.io"
  - "apps.open-cluster-management.io"
  resources:
  - apiservices
  - helmreleases
  - configmaps
  - clusterjoinrequests
  - deployments
  - ingresses
  - multiclusterhubs
  - namespaces
  - rolebindings
  - secrets
  - services
  - subjectaccessreviews
  - validatingwebhookconfigurations
  verbs:
  - watch

- apiGroups:
  - ""
  - "admissionregistration.k8s.io"
  - "apps"
  - "apps.open-cluster-management.io"
  - "mcm.ibm.com"
  - "monitoring.coreos.com"
  - "operator.open-cluster-management.io"
  resources:
  - deployments
  - deployments/finalizers
  - helmreleases
  - services
  - services/finalizers
  - servicemonitors
  - servicemonitors/finalizers
  - validatingwebhookconfigurations
  - multiclusterhubs
  - multiclusterhubs/finalizers
  - multiclusterhubs/status
  verbs:
  - update

- apiGroups:
  - "admissionregistration.k8s.io"
  - "apiextensions.k8s.io"
  - "apiregistration.k8s.io"
  - "hive.openshift.io"
  - "mcm.ibm.com"
  - "rbac.authorization.k8s.io"
  resources:
  - apiservices
  - clusterroles
  - clusterrolebindings
  - customresourcedefinitions
  - hiveconfigs
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - deletecollection

- apiGroups:
  - ""
  - "apps"
  - "apps.open-cluster-management.io"
  resources:
  - deployments
  - services
  - channels
  verbs:
  - delete

# RCM Dependancies
- apiGroups:
  - ""
  - "action.open-cluster-management.io"
  - "agent.open-cluster-management.io"
  - "cluster.open-cluster-management.io"
  - "work.open-cluster-management.io"
  - "app.k8s.io"
  - "apps.open-cluster-management.io"
  - "authorization.k8s.io"
  - "certificates.k8s.io"
  - "clusterregistry.k8s.io"
  - "cluster.open-cluster-management.io"
  - "config.openshift.io"
  - "compliance.mcm.ibm.com"
  - "hive.openshift.io"
  - "internal.open-cluster-management.io"
  - "inventory.open-cluster-management.io"
  - "mcm.ibm.com"
  - "multicloud.ibm.com"
  - "policy.open-cluster-management.io"
  - "proxy.open-cluster-management.io"
  - "rbac.authorization.k8s.io"
  - "view.open-cluster-management.io"
  - "operator.open-cluster-management.io"
  - "register.open-cluster-management.io"
  resources:
  - applications
  - applications/status
  - applicationrelationships
  - applicationrelationships/status
  - baremetalassets
  - baremetalassets/status
  - certificatesigningrequests
  - certificatesigningrequests/approval
  - channels
  - channels/status
  - managedclusteractions
  - managedclusteractions/status
  - clusterdeployments
  - managedclusterinfos
  - managedclusterinfos/status
  - managedclustersets
  - managedclustersetbindings
  - managedclusters
  - managedclusters/accept
  - managedclusters/status
  - managedclusterviews
  - managedclusterviews/status
  - manifestworks
  - manifestworks/status
  - clustermanagers
  - clusterroles
  - clusterrolebindings
  - clusterstatuses/aggregator
  - clusterversions
  - compliances
  - configmaps
  - deployables
  - deployables/status
  - deployableoverrides
  - deployableoverrides/status
  - endpoints
  - endpointconfigs
  - events
  - helmrepos
  - helmrepos/status
  - klusterletaddonconfigs
  - machinepools
  - namespaces
  - placementrules
  - placementrules/status
  - policies
  - policies/status
  - placementbindings
  - roles
  - rolebindings
  - secrets
  - signers
  - subscriptions
  - subscriptions/status
  - subjectaccessreviews
  - syncsets
  - syncsetinstances
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - deletecollection
  - patch
  - approve
  - escalate
