apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multiclusterhub-operator
  namespace: open-cluster-management
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: multiclusterhub-operator
  source: multiclusterhub-operator-registry
  sourceNamespace: open-cluster-management
  startingCSV: multiclusterhub-operator.v2.2.13
