# Copyright Contributors to the Open Cluster Management project

apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
spec:
  imagePullSecret: multiclusterhub-operator-pull-secret