# Copyright Contributors to the Open Cluster Management project

apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    installer.open-cluster-management.io/mce-subscription-spec: '{"channel": "stable-2.0","installPlanApproval": "Automatic","name":
      	"multicluster-engine","source": "multiclusterengine-catalog","sourceNamespace": "openshift-marketplace"}'
  name: multiclusterhub
spec:
  enableClusterBackup: false
