apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:siteconfig-controller-manager'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ .Values.org }}:{{ .Chart.Name }}:siteconfig-controller-manager'
subjects:
- kind: ServiceAccount
  name: siteconfig-controller-manager
  namespace: '{{ .Values.global.namespace }}'
