# Copyright Contributors to the Open Cluster Management project


resources:
- serviceaccount-foundation.yaml
- clusterrole-foundation.yaml
- clusterrolebinding-foundation.yaml
- clusterrole-admin-aggregate.yaml
- clusterrole-edit-aggregate.yaml
- clusterrole-view-aggregate.yaml
- clusterrole-clustermanageradmin.yaml
- clusterrole-clustermanageradmin-aggregate.yaml
