apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:volsync:clusterrole
  labels:
    app: volsync-addon-controller
    chart: volsync-addon-controller-{{ .Values.hubconfig.hubVersion }}
    release: volsync
    app.kubernetes.io/instance: volsync
    app.kubernetes.io/name: volsync-addon-controller
    component: volsync-addon-controller-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps", "events"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["get", "create"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests", "certificatesigningrequests/approval"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["signers"]
    verbs: ["approve"]
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclusters"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["work.open-cluster-management.io"]
    resources: ["manifestworks"]
    verbs: ["create", "update", "get", "list", "watch", "delete", "deletecollection", "patch"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["managedclusteraddons/finalizers"]
    verbs: ["update"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["clustermanagementaddons/finalizers"]
    verbs: ["update"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["clustermanagementaddons"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["addondeploymentconfigs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["managedclusteraddons"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["managedclusteraddons/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["config.openshift.io"]
    resources: ["infrastructures"]
    verbs: ["get", "list", "watch"]
