# Copyright Contributors to the Open Cluster Management project
apiVersion: v1
appVersion: "1.0.0"
description:  Helm chart for Open Cluster Management Cluster Backup Operator
name: cluster-backup-chart
version: 2.4.0
category: "Development"
keywords:
  - backup
  - restore