# Copyright Contributors to the Open Cluster Management project

# Default values for cluster-backup-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

org: open-cluster-management

global:
  pullPolicy: Always
  pullSecret: null
  imageOverrides:
    cluster_backup_controller: ""
  name: redhat-oadp-operator
  channel: stable-1.3
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace

hubconfig:
  nodeSelector: null
  replicaCount: 1
  proxyConfigs: {}
  tolerations:
    - key: dedicated
      operator: Exists
      effect: NoSchedule
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 70
      podAffinityTerm:
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: ocm-antiaffinity-selector
            operator: In
            values:
            - clusterbackup
    - weight: 35
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: ocm-antiaffinity-selector
            operator: In
            values:
            - clusterbackup

arch:
- amd64
- ppc64le
- s390x
- arm64

enabled: true

clusterbackup:
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"


BackupRestorePolicyName: backup-restore-enabled
ClusterCollisionPhase: BackupCollision

oadpOperator:
  name: redhat-oadp-operator
  channel: stable-1.3
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace