# Default values for console-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

org: open-cluster-management
global:
  imageOverrides:
    console: ""
  templateOverrides: {}
  # Available template overrides:
  # console_deployment_container_memory_request: <memory-value>
  # console_deployment_container_memory_limit: <memory-value>
  # console_deployment_container_cpu_request: <cpu-value>
  # console_deployment_container_cpu_limit: <cpu-value>
  namespace: default
  pullSecret: null
  pullPolicy: Always
  hubSize: Small
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
  hubVersion: ""
  ocpIngress: ""
  subscriptionPause: "false"
# clusterImageSets:
#   subscriptionPause: "false"
#   acmHiveOpenshiftReleaseUrl: "https://github.com/stolostron/acm-hive-openshift-releases.git"
