- repo_name: "cluster-permission"
  github_ref: "https://github.com/stolostron/cluster-permission.git"
  branch: "release-2.16"
  charts:
    - name: "cluster-permission"
      chart-path: "chart/"
      always-or-toggle: "toggle"
      imageMappings:
        cluster-permission: cluster_permission

- repo_name: "multicluster-role-assignment"
  github_ref: "https://github.com/stolostron/multicluster-role-assignment.git"
  branch: "release-2.16"
  charts:
      - name: "fine-grained-rbac"
        chart-path: "charts/fine-grained-rbac"
        crd-path: "config/crd/bases"
        always-or-toggle: "toggle"
        imageMappings:
          multicluster-role-assignment: multicluster_role_assignment