# Copyright Contributors to the Open Cluster Management project

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

resources:
- hive-operator.yaml
- subscription-operator.yaml
- cluster-manager-operator.yaml
