kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcm-controller
  labels:
    app: mcm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcm-controller
  template:
    metadata:
      labels:
        app: mcm-controller
    spec:
      serviceAccountName: hub-sa
      containers:
      - name: mcm-controller
        image: multicloud-manager:0.0.1
        args:
          - "/mcm-controller"
          - "--leader-elect=true"
          - "--enable-rbac=true"
          - "--enable-service-registry=true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
