global:
  apiUrl: ''
  baseDomain: ''
  imageOverrides:
    multicluster_role_assignment: ''
  namespace: default
  pullSecret: null
  templateOverrides: {}
hubconfig:
  clusterSTSEnabled: false
  nodeSelector: null
  ocpVersion: 4.12.0
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
