# Copyright (c) 2020 Red Hat, Inc.

global:
  imageOverrides:
    multicluster_role_assignment: quay.io/stolostron/multicluster-role-assignment:latest
  templateOverrides: {}
  namespace: default
  pullSecret: null
  pullPolicy: Always
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
  ocpVersion: 4.12.0
org: open-cluster-management
