name: Nightly Full Function Tests

# Controls when the action will run. 
on:
  # Triggers the workflow to run ~~every day~~ first of the month (will switch back to once a day once everything's working)
  # will trigger manually for testing
  schedule:
    - cron: "0 0 * * 1-5"

  # manual trigger
  workflow_dispatch:

jobs:
  function-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1' # The Go version to download (if necessary) and use.
      - name: Run FULL Function Tests
        run: |
          echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io/open-cluster-management -u "${{ secrets.QUAY_USER }}" --password-stdin
          echo "Running Nightly Function Tests ..."
          bash ./common/scripts/nightly-full-function-test.sh
        env:
          COLLECTIVE_TOKEN: ${{ secrets.COLLECTIVE_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_USER: ${{ secrets.QUAY_USER }}
          DOCKER_PASS: ${{ secrets.QUAY_TOKEN }}
          SLACKBOT_WEBHOOK_URL: ${{ secrets.SLACKBOT_WEBHOOK_URL }}
